#!/bin/bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install hostapd
sudo apt-get install dnsmasq
sudo systemctl stop hostapd
sudo systemctl stop dnsmasq

sudo mv /home/dhcpd.conf /etc/
sudo mv /home/dnsmasq.conf /etc


sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
iptables-restore < /etc/iptables.ipv4.nat


sudo apt-get install bridge-utils
sudo brctl addbr br0
sudo brctl addif br0 eth0
